version: "3.9"

services:
    app:
        build:
            context: ./__docker/php
            dockerfile: Dockerfile
        container_name: todo-php
        environment:
            APP_ENV: local
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: todo
            DB_USERNAME: todo_user
            DB_PASSWORD: todo_pass
        volumes:
            - ./:/var/www/html:delegated
            - ./__docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
        depends_on:
            - db
        networks:
            - todo-net


    web:
        image: nginx:1.27-alpine
        container_name: todo-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./__docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - todo-net

    db:
        image: mysql:8.0
        container_name: todo-mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: todo
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: todo_pass
            TZ: UTC
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        command: ["--default-authentication-plugin=mysql_native_password"]
        networks:
            - todo-net

volumes:
    dbdata:

networks:
    todo-net:
        driver: bridge
